---
version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_container
    ports:
      - '4568:4568'
      - '8055:8080'
    environment:
      - SERVICES=kinesis
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_CBOR_DISABLE=1
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

  spark-master:
    image: bde2020/spark-master:2.2.2-hadoop2.7
    container_name: spark-master
    volumes:
      - ./:/jar-files/
    ports:
      - 8082:8080
      - 7077:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker-1:
    image: bde2020/spark-worker:2.2.2-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - 8083:8081
    environment:
      - 'SPARK_MASTER=spark://spark-master:7077'
